### ISSUE TITLE
dtype_expr Branch Fails

### ISSUE THREAD

**Issue by jmdelahanty** [Tyelab/bruker_control#117]
It looks like the updated dtype branch that Annie has written where the datatypes are changed from `long` to `unsigned long` fails for an unknown reason.

Somehow, the serial transfer fails when trying to send/receive the  `pythonGo` or overall `go` signal in the Arduino code. It receives all the arrays but doesn't start actually iterating through them. I looked over what was going on quickly in the code but didn't notice anything that clearly illustrates why it's getting stuck there. The stack trace was this:

```
<class 'numpy.float32'>
Traceback (most recent call last):
  File "C:\Users\jdelahanty\Documents\gitrepos\bruker_control\main\serialtransfer_utils.py", line 181, in transfer_packet
    link.send(array_size, packet_id=packet_id)
  File "C:\Users\jdelahanty\Miniconda3\envs\bruker_control\lib\site-packages\pySerialTransfer\pySerialTransfer.py", line 439, in send
    message_len = constrain(message_len, 0, MAX_PACKET_SIZE)
  File "C:\Users\jdelahanty\Miniconda3\envs\bruker_control\lib\site-packages\pySerialTransfer\pySerialTransfer.py", line 101, in constrain
    if val < min_:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
Looking at the git history, it looks like in `trial_utils` instead of casting the numpy datatypes in the array to list, a dtype is specified to create a datatype of `np.float32`. It looks like `pySerialTransfer` doesn't like packing this data type into the packets sent over the Serial to UART converter at least it doesn't without properly changing the stuffing of data into the buffer. Something around [here](https://github.com/Tyelab/bruker_control/blob/6b855b4414ae0723cfaf004f2e205e1dc3c5deae/main/serialtransfer_utils.py#L189) likely needs to be changed, but how specifically I'm not sure. If we change the datatype in that or, instead of having it hardcoded, have it inferred from the array type that would be best maybe. I think that Python natively uses `uint32` for Serial communications and it was easiest to just keep things in that format by not specifying a dtype.

It also looks like it committed stuff that Annie did but has me as the person who committed it? I think I setup my collaborative coding stuff incorrectly on accident.

**Comment by jmdelahanty** [comment]
It looks like it'd be a simple fix to basically not coerce the dtype into `np.float32`, but perhaps it's better practice to use it.

**Comment by jmdelahanty** [comment]
Now in Develop.
